//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salão_de_beleza__VIVIANE_E_LUANA.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salão_de_beleza__VIVIANE_E_LUANA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_1_780x520 {
            get {
                object obj = ResourceManager.GetObject("11-1-780x520", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _184566075_interior_view_of_a_modern_hair_and_beauty_salon {
            get {
                object obj = ResourceManager.GetObject("184566075-interior-view-of-a-modern-hair-and-beauty-salon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _73b3e4792f78ea9ed801b54ab205eebd {
            get {
                object obj = ResourceManager.GetObject("73b3e4792f78ea9ed801b54ab205eebd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _845ed8d1f62c544d9a75fab0a9acda30 {
            get {
                object obj = ResourceManager.GetObject("845ed8d1f62c544d9a75fab0a9acda30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Abstract_Grey_Artistic_HD_Desktop_Wallpaper_100223 {
            get {
                object obj = ResourceManager.GetObject("Abstract-Grey-Artistic-HD-Desktop-Wallpaper-100223", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Abstract_Grey_Artistic_HD_Desktop_Wallpaper_1002231 {
            get {
                object obj = ResourceManager.GetObject("Abstract-Grey-Artistic-HD-Desktop-Wallpaper-1002231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Abstract_Grey_Artistic_HD_Desktop_Wallpaper_1002232 {
            get {
                object obj = ResourceManager.GetObject("Abstract-Grey-Artistic-HD-Desktop-Wallpaper-1002232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_screen_39 {
            get {
                object obj = ResourceManager.GetObject("black-screen_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_12_de_ago__de_2026__10_57_58 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 12 de ago. de 2026, 10_57_58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_13_de_ago__de_2026__07_47_06 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 13 de ago. de 2026, 07_47_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_13_de_ago__de_2026__07_47_11 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 13 de ago. de 2026, 07_47_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_13_de_ago__de_2026__08_48_39 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 13 de ago. de 2026, 08_48_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Escala_Cinza_com_Vermelho_Salão_de_Cabeleireiro_Beleza_Capa_Facebook {
            get {
                object obj = ResourceManager.GetObject("Escala Cinza com Vermelho Salão de Cabeleireiro Beleza Capa Facebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Escala_Cinza_com_Vermelho_Salão_de_Cabeleireiro_Beleza_Capa_Facebook__1_ {
            get {
                object obj = ResourceManager.GetObject("Escala Cinza com Vermelho Salão de Cabeleireiro Beleza Capa Facebook (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f5ebff7e59366c16574f4299a24ad5a1 {
            get {
                object obj = ResourceManager.GetObject("f5ebff7e59366c16574f4299a24ad5a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2___1_ {
            get {
                object obj = ResourceManager.GetObject("images (2) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__3___1_ {
            get {
                object obj = ResourceManager.GetObject("images (3) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_aesthetic_creative_design_close_up_of_white_cardboard_background_with_old_picture_image_13613553 {
            get {
                object obj = ResourceManager.GetObject("pngtree-aesthetic-creative-design-close-up-of-white-cardboard-background-with-old" +
                        "-picture-image_13613553", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_announcement_warning_alert_symbol_vector_png_image_34702248 {
            get {
                object obj = ResourceManager.GetObject("pngtree-announcement-warning-alert-symbol-vector-png-image_34702248", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_gold_female_silhouette_barbershop_logo_png_image_4379001 {
            get {
                object obj = ResourceManager.GetObject("pngtree-gold-female-silhouette-barbershop-logo-png-image_4379001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_gold_female_silhouette_barbershop_logo_png_image_4379001__1_ {
            get {
                object obj = ResourceManager.GetObject("pngtree-gold-female-silhouette-barbershop-logo-png-image_4379001 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_woman_getting_haircut_by_hairdresser_highlights_people_women_vector_png_image_12592602__1_ {
            get {
                object obj = ResourceManager.GetObject("pngtree-woman-getting-haircut-by-hairdresser-highlights-people-women-vector-png-i" +
                        "mage_12592602 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap space_acg_emmaleague_34 {
            get {
                object obj = ResourceManager.GetObject("space-acg-emmaleague-34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2026_08_12_at_09_29_08 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2026-08-12 at 09.29.08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
